services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-cliente
    ports:
      - "8000:8000"
    volumes:
      - ./api_cliente_cartao:/var/www
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: /bin/bash -c "composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container-cliente
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbcliente
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge